modLoader="lowcodefml"
loaderVersion="[37,51)"
license="Apache-2.0"
issueTrackerURL="${github_repo}/issues"
logoFile="assets/${mod_id}/icon.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${display_name}"
authors="AnAwesomGuy"
description="${description}"
displayURL="http://modrinth.com/mod/${modrinth_id}"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="(,1.20.5)"