modLoader="lowcodefml"
loaderVersion="[1.0,)"
license="Apache-2.0"
issueTrackerURL="${github_repo}/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${display_name}"
authors="AnAwesomGuy"
description="${description}"
logoFile="assets/${mod_id}/icon.png"
displayURL="http://modrinth.com/mod/${modrinth_id}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="(1.20.5,)"